# CIS164 Final Project Notebook Template

This notebook is a **template** showing the recommended structure for your final project.

A good notebook should read like a **story**:
1. What question are you asking?
2. What data are you using?
3. How did you clean and analyze it?
4. What did you find?

Replace the bullet points below with your own content.

# Research Question

Include:
- A clear **research question**
- Why the question is interesting or important

Example:

**Research Question**
- Is there a relationship between **average sleep hours and depression prevalence** across different age groups?

**Why this matters**
- Sleep has known links to mental health
- Understanding patterns could help identify at‑risk populations

# Dataset Description

Explain the dataset before using it.

Include:
- Where the dataset came from
- What population it represents
- Important variables used in your analysis
- Possible limitations or bias

Example:

**Dataset Source**
- CDC Behavioral Risk Factor Surveillance System (BRFSS)

**Key Variables**
- `age`
- `sleep_hours`
- `depression_status`

**Limitations**
- Self‑reported data
- Missing values in some variables

# Import Libraries

Explain briefly what libraries you are using and why.

Example:
- **pandas** for data manipulation
- **numpy** for numerical operations
- **matplotlib / seaborn** for visualization

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Data

Steps:
- Load the dataset
- Display the first few rows
- Confirm columns look correct

Example explanation:
- The dataset is loaded from a CSV file
- We preview the data to confirm it loaded correctly

In [3]:
event = pd.read_excel("Total Fatal Crashes by Event.xlsx") #Cleaned: crashes_by_event
road_crashes =pd.read_excel("Fatal Crashes by Road.xlsx") #Cleaned: total_road_crashes
fatalities = pd.read_excel("Fatalities.xlsx") #Cleaned: fatalities_by_state
person_killed = pd.read_excel("Person Killed.xlsx") #Cleaned: type_person_killed
road_deaths = pd.read_excel("Total Deaths by Road.xlsx") #Cleaned: total_road_deaths
age = pd.read_excel("Victim Age.xlsx") #Cleaned: victim_age
pedestrians = pd.read_excel("Pedestrian Deaths.xlsx") #Cleaned: pedestrian_deaths
killed_driver_bac = pd.read_excel("Killed Driver BAC.xlsx") #Cleaned: driver_victim_bac
crash_driver_bac = pd.read_excel("Fatal Crash Driver BAC.xlsx") #Cleaned: all_driver_bac
restraint_use = pd.read_excel("Restraint Use Data.xlsx") #Cleaned: restraints
rollover = pd.read_excel("Rollover Data.xlsx") #Cleaned: rollovers
surviving_driver_bac = pd.read_excel("Surviving Driver BAC.xlsx") #Cleaned: living_driver_bac
vehicle = pd.read_excel("Vehicle Type.xlsx") #Cleaned: vehicles
vehicle.head()
#The files came in a bunch of pieces, but for the assignment I just printed out the first 5 rows of 1 file to reduce clutter

,Unnamed: 0,Unnamed: 1,Vehicle Type,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,NaN,Passenger Cars,NaN,Light Trucks,NaN,Large Trucks,NaN,Buses,NaN,Other Vehicles/Unknown,NaN,Total,NaN,Motorcycles,NaN,Total Occupants Killed
1,State,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number,Percent
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alabama,335,40,364,43.4,29,3.5,0,0,16,1.9,744,88.8,94,11.2,838,100
4,Alaska,13,27.1,23,47.9,1,2.1,0,0,3,6.3,40,83.3,8,16.7,48,100

# Data Cleaning

Explain what needed to be fixed before analysis.

Possible tasks:
- Handling missing values
- Converting column types
- Filtering rows
- Creating new columns

Example explanation:
- Convert sleep hours to numeric
- Remove rows with missing depression data

In [4]:
event2 = event.iloc[1:].reset_index(drop=True)
for index, val in enumerate(event2.iloc[0]):
    if pd.isna(val):
        event2.iloc[0, index] = event2.iloc[0, index+1]


event2.iloc[2] = event2.iloc[0]+" " + event2.iloc[1]
event2.iloc[2,0] = "State"
event2.columns = event2.iloc[2]
event2.columns.name = None
crashes_by_event = event2.iloc[3:].reset_index(drop=True)
crashes_by_event = crashes_by_event.apply(pd.to_numeric, errors = "ignore")
crashes_by_event8 = crashes_by_event.drop(columns = ["Other Number", "Other Percent", "Unknown Number", "Unknown Percent"])

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\4282668067.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  crashes_by_event = crashes_by_event.apply(pd.to_numeric, errors = "ignore")

In [5]:
road_crashes.columns = road_crashes.iloc[2] + " Crashes"
road_crashes.columns.name = None
total_road_crashes = road_crashes.iloc[4:].reset_index(drop=True)
total_road_crashes = total_road_crashes.apply(pd.to_numeric, errors = "ignore")
total_road_crashes8 = total_road_crashes.drop(columns=["State Crashes"])

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\579640847.py:4: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  total_road_crashes = total_road_crashes.apply(pd.to_numeric, errors = "ignore")

In [6]:
person_killed2 = person_killed.copy()
for index in range(len(person_killed.columns)-1, 6, -1):
    person_killed2.iloc[0, index] = person_killed.iloc[0, index-2]

person_killed2.iloc[0, 6] = "Motorcyclist"
person_killed2.iloc[0,0] = "State"

for index, val in enumerate(person_killed2.iloc[0]):
    if pd.isna(val):
        person_killed2.iloc[0, index] = person_killed2.iloc[0, index+1]
person_killed2.iloc[2] = person_killed2.iloc[0]+ " " + person_killed2.iloc[1]

person_killed2.columns = person_killed2.iloc[2]
person_killed2.columns.name = None
type_person_killed = person_killed2.iloc[3:].reset_index(drop=True)
type_person_killed.rename(columns = {"State State": "State"}, inplace=True)
type_person_killed = type_person_killed.apply(pd.to_numeric, errors = "ignore")
type_person_killed8 = type_person_killed.drop(columns = ["State", "Other/Unknown Number", "Other/Unknown Percent"])
type_person_killed8 = type_person_killed8[type_person_killed8.columns.dropna()]

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\3972875291.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Total Killed' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  person_killed2.iloc[0, index] = person_killed.iloc[0, index-2]
C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\3972875291.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Total Killed' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  person_killed2.iloc[0, index] = person_killed2.iloc[0, index+1]
C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\3972875291.py:17: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  type_person_killed = type_person_killed.apply(pd.to_numeric, errors = "ignore")

In [7]:
road_deaths.columns = road_deaths.iloc[2] + " Deaths"
road_deaths.columns.name = None
total_road_deaths = road_deaths.iloc[4:].reset_index(drop=True)
total_road_deaths = total_road_deaths.apply(pd.to_numeric, errors = "ignore")
total_road_deaths8 = total_road_deaths.drop(columns=["State Deaths"])

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\2288010528.py:4: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  total_road_deaths = total_road_deaths.apply(pd.to_numeric, errors = "ignore")

In [8]:
fatalities_by_state = fatalities.iloc[1:].reset_index(drop=True)
fatalities_by_state8 = fatalities_by_state.drop(columns=["State"])

In [9]:
age.columns = "Age " + age.iloc[0]
age.columns.name = None
victim_age = age.iloc[2:].reset_index(drop=True)
victim_age = victim_age.apply(pd.to_numeric, errors = "ignore")
victim_age8 = victim_age.drop(columns = ["Age State"])

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\4019118734.py:4: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  victim_age = victim_age.apply(pd.to_numeric, errors = "ignore")

In [10]:
pedestrian_deaths = pedestrians.iloc[1:].sort_values(by= "State").reset_index(drop=True)
pedestrian_deaths = pedestrian_deaths[["State", "Pedestrians Killed", "Population (Thousands)", "Pedestrian Fatality Rate per 100,000 Population"]]
pedestrian_deaths = pedestrian_deaths.apply(pd.to_numeric, errors = "ignore")
pedestrian_deaths8 = pedestrian_deaths.drop(columns = ["State"])

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\1962759674.py:3: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  pedestrian_deaths = pedestrian_deaths.apply(pd.to_numeric, errors = "ignore")

In [11]:
killed_driver_bac2 = killed_driver_bac.copy()

for i, val in enumerate(killed_driver_bac2.iloc[0]):
    if pd.isna(val):
        killed_driver_bac2.iloc[0, i] = killed_driver_bac.iloc[0, i+1]

killed_driver_bac2.iloc[2] = "Victim " + killed_driver_bac2.iloc[0] + " " + killed_driver_bac2.iloc[1]
killed_driver_bac2.iloc[2, 0] = "State"
killed_driver_bac2.columns = killed_driver_bac2.iloc[2]
killed_driver_bac2.columns.name = None

driver_victim_bac = killed_driver_bac2.iloc[3:].reset_index(drop=True)
driver_victim_bac = driver_victim_bac.apply(pd.to_numeric, errors = "ignore")
driver_victim_bac8 = driver_victim_bac.drop(columns = {"Victim Total Drivers Killed Percent", "State"})

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\2097505884.py:13: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  driver_victim_bac = driver_victim_bac.apply(pd.to_numeric, errors = "ignore")

In [12]:
cdb = crash_driver_bac.copy()
for i, val in enumerate(crash_driver_bac.iloc[0]):
    if pd.isna(val):
        cdb.iloc[0, i] = crash_driver_bac.iloc[0, i+1]

cdb.iloc[2] = "All " + cdb.iloc[0] +" " + cdb.iloc[1]
cdb.iloc[2, 0] = "State"
cdb.columns = cdb.iloc[2]
cdb.columns.name = None

all_driver_bac = cdb.iloc[3:].reset_index(drop=True)
all_driver_bac = all_driver_bac.apply(pd.to_numeric, errors = "ignore")
all_driver_bac8 = all_driver_bac.drop(columns = {"All Total Drivers Involved in Fatal Crashes Percent", "State"})

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\4227290427.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  all_driver_bac = all_driver_bac.apply(pd.to_numeric, errors = "ignore")

In [13]:
restraint_use2 = restraint_use.copy()
restraint_use2.iloc[1] = restraint_use.columns
for i,val in enumerate(restraint_use2.iloc[1]):
    if val == f"Unnamed: {i}":
        restraint_use2.iloc[1, i] = restraint_use.columns[i+1]

restraint_use2.iloc[1, 0] = "State"
restraint_use2.columns = restraint_use2.iloc[1]+ " "+restraint_use2.iloc[0]
restraint_use2.rename(columns={"State State": 'State', "Total Number": "Restraint Total"}, inplace=True)
restraints = restraint_use2.iloc[2:].reset_index(drop=True)
restraints = restraints.apply(pd.to_numeric, errors = "ignore")
restraints8 = restraints.drop(columns = ["Total Percent", "State"])

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\1585274882.py:11: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  restraints = restraints.apply(pd.to_numeric, errors = "ignore")

In [14]:
rollover2 = rollover.copy()
rollover2 = rollover2.drop(columns = ["Unnamed: 13", "Unnamed: 14", "Unnamed: 15"])
rollover3 = rollover2.copy()

for i,val in enumerate(rollover2.iloc[0]):
    if i > 0:
        if pd.isna(val):
            rollover3.iloc[0, i] = rollover2.iloc[0, i-1]
for i,val in enumerate(rollover3.iloc[0]):
    if i > 0:
        if pd.isna(val):
            rollover3.iloc[0, i] = rollover3.iloc[0, i-1]

for i,val in enumerate(rollover2.iloc[1]):
    if i > 0:
        if pd.isna(val):
            rollover3.iloc[1, i] = rollover2.iloc[1, i-1]

rollover3.iloc[0, 0] = "1"
rollover3.iloc[1, 0] = "2"
rollover3.columns = rollover3.iloc[0]+ " "+ rollover3.iloc[1] + " " + rollover3.iloc[2]
rollover3.rename(columns = {"1 2 State": "State", }, inplace=True)

rollovers = rollover3.iloc[4:].reset_index(drop=True)
rollovers = rollovers.apply(pd.to_numeric, errors = "ignore")
rollovers8 = rollovers.drop(columns = ["Passenger Cars Total Num", "Total Total Num", "State"])

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\3209948738.py:25: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  rollovers = rollovers.apply(pd.to_numeric, errors = "ignore")

In [15]:
sdb = surviving_driver_bac.copy()
for i, val in enumerate(surviving_driver_bac.iloc[0]):
    if pd.isna(val):
        sdb.iloc[0, i] = surviving_driver_bac.iloc[0, i+1]

sdb.iloc[2] = "Survivor " + sdb.iloc[0] +" " + sdb.iloc[1]
sdb.iloc[2, 0] = "State"
sdb.columns = sdb.iloc[2]
sdb.columns.name = None

living_driver_bac = sdb.iloc[3:].reset_index(drop=True)
living_driver_bac = living_driver_bac.apply(pd.to_numeric, errors = "ignore")
living_driver_bac8 = living_driver_bac.drop(columns=["Survivor Total Surviving Drivers Involved in Fatal Crashes Percent", "State"])

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\3813712368.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  living_driver_bac = living_driver_bac.apply(pd.to_numeric, errors = "ignore")

In [20]:
v = vehicle.copy()
for i, val in enumerate(vehicle.iloc[0]):
    if pd.isna(val):
        v.iloc[0, i] = vehicle.iloc[0, i+1]

v.iloc[2] = "Vehicle: " + v.iloc[0] +" " + v.iloc[1]
v.iloc[2, 0] = "State"
v.columns = v.iloc[2]
v.columns.name = None

vehicles = v.iloc[3:].reset_index(drop=True)
vehicles = vehicles.apply(pd.to_numeric, errors = "ignore")
vehicles8 = vehicles.drop(columns = {"State"})

C:\Users\marsh\AppData\Local\Temp\ipykernel_5216\1007623987.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  vehicles = vehicles.apply(pd.to_numeric, errors = "ignore")

In [ ]:
accident_data_by_state = pd.concat([crashes_by_event, total_road_crashes8, fatalities_by_state8, type_person_killed8, total_road_deaths8, victim_age8, pedestrian_deaths8, driver_victim_bac8, all_driver_bac8, restraints8, rollovers8, living_driver_bac8, vehicles8], axis=1)
accident_data_by_state.to_excel("Accident Data by State.xlsx", index=False)

# Exploratory Data Analysis (EDA)

Goal:
- Understand the structure of the data before drawing conclusions

Possible steps:
- Summary statistics
- Value counts
- Group comparisons

Example questions:
- What is the average sleep duration?
- How many individuals report depression?

In [21]:
accident_data_by_state.describe()

,Motor Vehicle Number,Motor Vehicle Percent,Nonmotorist Number,Nonmotorist Percent,Fixed Object Number,Fixed Object Percent,Object Not Fixed Number,Object Not Fixed Percent,Overturn Number,Overturn Percent,...,Vehicle: Buses Number,Vehicle: Buses Percent,Vehicle: Other Vehicles/Unknown Number,Vehicle: Other Vehicles/Unknown Percent,Vehicle: Total Number,Vehicle: Total Percent,Vehicle: Motorcycles Number,Vehicle: Motorcycles Percent,Vehicle: Total Occupants Killed Number,Vehicle: Total Occupants Killed Percent
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,...,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.0
mean,581.423077,39.428846,313.346154,19.034615,398.884615,28.678846,41.884615,3.069231,96.730769,8.434615,...,1.230769,0.086538,30.538462,2.653846,990.230769,80.175000,243.653846,19.825000,1233.884615,100.0
std,2081.344384,5.104221,1131.964956,7.742976,1424.232654,7.227218,149.823511,1.227550,345.851329,5.938406,...,4.655233,0.230114,109.458464,2.052207,3538.570669,6.100141,872.808401,6.100141,4410.302069,0.0
min,12.000000,21.600000,6.000000,7.700000,7.000000,12.900000,1.000000,0.800000,1.000000,1.500000,...,0.000000,0.000000,0.000000,0.000000,21.000000,57.100000,6.000000,9.200000,27.000000,100.0
25%,97.250000,37.250000,29.750000,13.475000,55.500000,24.175000,7.000000,2.275000,20.750000,3.975000,...,0.000000,0.000000,2.750000,1.275000,187.250000,77.375000,38.750000,16.325000,224.250000,100.0
50%,221.500000,40.000000,110.500000,17.950000,157.500000,28.750000,14.500000,2.800000,35.500000,6.900000,...,0.000000,0.000000,11.000000,2.350000,396.500000,81.650000,89.500000,18.350000,479.500000,100.0
75%,370.500000,42.925000,181.750000,22.725000,279.250000,33.300000,27.500000,4.100000,60.250000,10.375000,...,1.000000,0.000000,23.500000,3.600000,685.750000,83.675000,173.000000,22.625000,840.250000,100.0
max,15117.000000,47.600000,8147.000000,41.000000,10371.000000,47.200000,1089.000000,6.400000,2515.000000,27.300000,...,32.000000,1.300000,794.000000,10.700000,25746.000000,90.800000,6335.000000,42.900000,32081.000000,100.0

# Visualizations

Each visualization should follow this pattern:

1. Markdown explaining **what the plot shows**
2. Code generating the plot
3. Markdown interpreting the results

Example explanation:
- This boxplot compares sleep hours across age groups

In [19]:
sns.boxplot(x="age_group", y="sleep_hours", data=df_clean)
plt.title("Sleep Duration by Age Group")
plt.show()

NameError: name 'df_clean' is not defined

**Interpretation Example**

- Younger age groups appear to have slightly lower sleep duration
- Older groups show less variation
- Differences appear moderate but require further analysis

# Key Findings

Summarize the main results.

Example:
- Average sleep duration decreases slightly with age
- Higher depression prevalence appears in younger groups
- The relationship between sleep and depression appears moderate

# Limitations

Discuss weaknesses in the analysis.

Possible examples:
- Small sample size
- Missing data
- Correlation does not imply causation

# Conclusion

Answer the research question directly.

Example:

- There appears to be a **moderate relationship between sleep duration and depression prevalence**
- Further analysis using regression models could explore this relationship more rigorously

# Citations

Include:
- Dataset source
- Any helpful resources or documentation used

Example:
- CDC BRFSS Dataset
- Pandas documentation

## Additional Notes From Class

- The notebook is a critical piece of communication, don't neglect it
- The notebook needs to be easily accessible. Your audience may not be experts in your field and/or the code you've written.
- The notebook needs to be able to run from top-to-bottom.
- Every major step should include **formatted** markdown explaining what you are doing and why.
- This notebook will contain more analyses than you will put in your presentation.
    - That said, remove code that isn't useful or that you were just testing.
- Use meaningful variable names, especially important when you're modifying whole dataframes.
- Label plots, don't rely on defaults
    - Add units to your axes labels if known.